# Generated by Django 5.0.6 on 2024-06-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_likes_count_like_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
