# Generated by Django 5.0.6 on 2024-06-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_likes_count_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liked',
            field=models.BooleanField(default=False, verbose_name='Лайкнуто'),
        ),
    ]
