# Generated by Django 5.0.6 on 2024-06-27 18:44

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_notification_options_remove_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='full_description',
            field=markdownx.models.MarkdownxField(verbose_name='Полное описание'),
        ),
    ]
